### ISSUE TITLE
CSV file has multiple tables/not standard

### ISSUE THREAD

**Issue by ashkjones** [TheD2Lab/gazepoint-data-analysis#12]
`collapsedSequences.csv` file does not have the standard format where first row is headers and following rows are data. There are two "tables" with different headers in one file. This makes processing the data much more difficult using Pandas or other libraries

Please make separate files for 
1) mapping AOI to letter 
2) Pattern metrics

I understand this was done to keep the information in one place, but descriptive filenames (or a folder name) should suffice in conveying to users that file_1 is needed to interpret file_2.

[csv file definition](https://www.rfc-editor.org/rfc/rfc4180#page-2)

**Comment by angeloryan** [comment]
I'll make sure to implement these changes in the refactor

**Comment by angeloryan** [comment]
In refactored code, collapsed sequences and AOI mappings are separate files
