### ISSUE TITLE
Fix Cleansing Process

### ISSUE THREAD

**Issue by ashkjones** [TheD2Lab/gazepoint-data-analysis#17]
# Update
There is nothing wrong with the cleansing process. The issue was with p35's data; only one eye was detected by gazepoint.

## Overview of Issue
- Cleansing removed almost all data from p35
- Look for portions that might cause "over cleansing". Potential causes:
  - pupil dilation
  - only one eye captured

## Notes
- Angelo suggested implementing fix on the refactor branch

**Comment by ashkjones** [comment]
@angeloryan @mhalderman12 Where should I put the file cleansing process code and from which file should I call it from? Should the cleansed gaze files be held in the Parameter class?

**Comment by angeloryan** [comment]
@ashkjones I would recommend that the file cleaning process be isolated to the DataEntry class. We currently have 4 arrays; allGaze, fixation, cleansedAllGaze, and cleansedFixation. allGaze and fixation are populated using the process() fuction as lines are fed in by checking which category a line belongs to; by extension, how I had originally planned to populate the cleansed variants was by checking if each isolated line is valid as they are fed in. So in other words, something like this:

> process(String[] currLine) {
>     ArrayList<String> line = Arrays.asList(currLine)
>     allGazeData.add(line);
> 
>    if (line is fixation) fixation.add(line)
>    
>    if (line is valid) {
>       cleansedAllGaze.add(line)
>       if (line is fixation) cleansedFixation.add(line)
>    }
> }

Feel free to use any implementation you deem appropriate, but again I would suggest to isolate it all within the DataEntry class so as to provide a layer of abstraction.

**Comment by ashkjones** [comment]
Close with #19
