### ISSUE TITLE
NegativeArraySizeException when AOI has no valid entries

### ISSUE THREAD

**Issue by ashkjones** [TheD2Lab/gazepoint-data-analysis#21]
Error Running` p22_all_gaze_approach.csv` file (the Single AOI version). `RPM` AOI is having all lines cleansed, so an empty array is passed to `Saccades.getAllSaccadeLength`

My Terminal Output:
>  Analyzing p22_approach
> java.lang.NegativeArraySizeException: -1
>         at analysis.Saccades.getAllSaccadeLength(Saccades.java:130)
>         at analysis.Saccades.analyze(Saccades.java:39)
>         at analysis.Analysis.generateResults(Analysis.java:109)
>         at analysis.AreaOfInterests.generateAOIs(AreaOfInterests.java:58)
>         at analysis.Analysis.run(Analysis.java:63)
>         at analysis.UserInterface.runAnalysis(UserInterface.java:649)
>         at analysis.UserInterface.lambda$2(UserInterface.java:553)
>         at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
>         at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
>         at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
>         at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
>         at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
>         at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
>         at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
>         at java.desktop/java.awt.Component.processEvent(Component.java:6386)
>         at java.desktop/java.awt.Container.processEvent(Container.java:2266)
>         at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
>         at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
>         at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
>         at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
>         at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
>         at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
>         at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
>         at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
>         at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
>         at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
>         at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
>         at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
>         at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
>         at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
>         at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
>         at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
>         at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
>         at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
>         at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
>         at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
>         at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
>         at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
>         at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
>         at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
>         at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
>         at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
>

**Comment by angeloryan** [comment]
Fixed by adding a check to see if list is empty to deal with the edge case, see 9ad6da0 and 0c1bbb4
