### ISSUE TITLE
AOI_DGMs does not include transitions for the last AOI

### ISSUE THREAD

**Issue by ashkjones** [TheD2Lab/gazepoint-data-analysis#22]
The last AOI does not have transition information 

Contents of `p1_AOI_DGMs.csv` :
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/ashleyjones/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/ashleyjones/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">

</head>

<body link="#467886" vlink="#96607D">

Total Number of   Fixations | Sum of all fixation duration (s) | Mean fixation duration (s) | Median fixation duration (s) | St.Dev. of fixation durations (s) | Min. fixation duration (s) | Max. fixation duration (s) | total number of saccades | sum of all saccade length | mean saccade length | median saccade length | StDev of saccade lengths | min saccade length | max saccade length | sum of all saccade durations | mean saccade duration | median saccade duration | StDev of saccade durations | Min. saccade duration | Max. saccade duration | scanpath duration | fixation to saccade ratio | Average Peak Saccade Velocity | sum of all absolute degrees | mean absolute degree | median absolute degree | StDev of absolute degrees | min absolute degree | max absolute degree | sum of all relative degrees | mean relative degree | median relative degree | StDev of relative degrees | min relative degree | max relative degree | convex hull area | stationary entropy | transition entropy | Average Blink Rate per Minute | total number of valid recordings | average pupil size of left eye | average pupil size of right eye | average pupil size of both eyes | total number of L mouse clicks | AOI | Proportion of fixations spent in AOI | Proportion of fixations durations spent in   AOI | AOI Pair_0 | Transition Count_0 | Proportion including self-transitions_0 | Proportion excluding self-transitions_0 | AOI Pair_1 | Transition Count_1 | Proportion including self-transitions_1 | Proportion excluding self-transitions_1 | AOI Pair_2 | Transition Count_2 | Proportion including self-transitions_2 | Proportion excluding self-transitions_2 | AOI Pair_3 | Transition Count_3 | Proportion including self-transitions_3 | Proportion excluding self-transitions_3 | AOI Pair_4 | Transition Count_4 | Proportion including self-transitions_4 | Proportion excluding self-transitions_4 | AOI Pair_5 | Transition Count_5 | Proportion including self-transitions_5 | Proportion excluding self-transitions_5 | AOI Pair_6 | Transition Count_6 | Proportion including self-transitions_6 | Proportion excluding self-transitions_6
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
1220 | 280.75371 | 0.23012599 | 0.20605 | 0.16134561 | 0.01971 | 1.26611 | 182 | 11110.5005 | 61.0467062 | 61.838749 | 35.0754361 | 2.33663419 | 186.241739 | 8.81119 | 0.04841313 | 0.00672 | 0.10318519 | 0.00598 | 0.51611 | 289.5649 | 31.8633136 | 199.415036 | 80768.9558 | 66.2583723 | 84.5952136 | 30.5173982 | 0.06855584 | 90 | 122969.748 | 100.960384 | 96.8105987 | 57.3476616 | 0.16040771 | 180 | 19746.1493 | 0 | 0 | 11 | 1220 | 5.36803928 | 5.76511987 | 5.56657957 | 0 | AI | 0.01032837 | 0.01066565 | Alt_VSI | 0 | 0 | 0 | AI | 111 | 0.2494382 | 0.67682927 | ASI | 14 | 0.03146067 | 0.08536585 | TI_HSI | 12 | 0.02696629 | 0.07317073 | SSI | 24 | 0.05393258 | 0.14634146 | Window | 3 | 0.00674157 | 0.01829268 | RPM | 0 | 0 | 0
1813 | 376.4515 | 0.2076401 | 0.16718 | 0.19457307 | 0.01837 | 2.5921 | 538 | 69559.4308 | 129.292622 | 110.380352 | 118.679715 | 0.58307776 | 987.133352 | 40.06757 | 0.07447504 | 0.02002 | 0.12205941 | 0.00591 | 0.96436 | 416.51907 | 9.39541629 | 264.945062 | 116141.701 | 64.0958617 | 81.9462693 | 31.3250111 | 0.01089918 | 90 | 177709.114 | 98.1276171 | 94.0136745 | 57.2989715 | 0.2517431 | 180 | 571405.333 | 0 | 0 | 11 | 1813 | 5.38345076 | 5.77717224 | 5.5803115 | 0 | No AOI | 0.01643904 | 0.01510135 | Alt_VSI | 116 | 0.32044199 | 0.42804428 | AI | 0 | 0 | 0 | ASI | 45 | 0.12430939 | 0.16605166 | TI_HSI | 32 | 0.08839779 | 0.11808118 | SSI | 70 | 0.19337017 | 0.25830258 | Window | 2 | 0.00552486 | 0.00738007 | RPM | 6 | 0.01657459 | 0.02214022
949 | 303.50748 | 0.31981821 | 0.26801 | 0.22638295 | 0.01953 | 1.35278 | 340 | 18641.898 | 54.8291117 | 48.0371996 | 35.2494752 | 2.70295944 | 194.833281 | 9.54844 | 0.02808365 | 0.00672 | 0.13692983 | 0.00397 | 2.31738 | 313.05592 | 31.7860802 | 137.110164 | 56959.2955 | 60.083645 | 69.408199 | 30.5301501 | 0 | 90 | 87697.4771 | 92.6055724 | 90.2870232 | 52.5434131 | 0.12680859 | 180 | 33558.5337 | 0 | 0 | 11 | 949 | 5.4139859 | 5.78900949 | 5.6014977 | 0 | Alt_VSI | 0.00819461 | 0.0116456 | Alt_VSI | 11 | 0.1 | 0.12941176 | AI | 56 | 0.50909091 | 0.65882353 | ASI | 0 | 0 | 0 | TI_HSI | 2 | 0.01818182 | 0.02352941 | SSI | 12 | 0.10909091 | 0.14117647 | Window | 2 | 0.01818182 | 0.02352941 | RPM | 2 | 0.01818182 | 0.02352941
259 | 79.46527 | 0.30681571 | 0.32135 | 0.1504733 | 0.02655 | 0.95764 | 36 | 1806.86298 | 50.1906383 | 48.7329892 | 20.7261561 | 14.2843212 | 112.58104 | 0.24 | 0.00666667 | 0.00665 | 2.78E-04 | 0.00599 | 0.0072 | 79.70527 | 331.105292 | 64.0854705 | 17062.3361 | 66.1330857 | 76.8587521 | 27.6421425 | 1.75160058 | 90 | 23741.1647 | 92.3780726 | 87.3184787 | 54.0909826 | 0.39633284 | 180 | 23141.9844 | 0 | 0 | 11 | 259 | 5.45627815 | 5.86123031 | 5.65875423 | 0 | ASI | 0.00219187 | 0.00301797 | Alt_VSI | 11 | 0.06626506 | 0.1047619 | AI | 67 | 0.40361446 | 0.63809524 | ASI | 10 | 0.06024096 | 0.0952381 | TI_HSI | 0 | 0 | 0 | SSI | 15 | 0.09036145 | 0.14285714 | Window | 0 | 0 | 0 | RPM | 2 | 0.01204819 | 0.01904762
136 | 38.32742 | 0.28181926 | 0.22757 | 0.22375214 | 0.07971 | 1.59412 | 64 | 5145.3644 | 80.3963188 | 55.2827879 | 73.8657815 | 2.9141189 | 413.158563 | 0.75062 | 0.01172844 | 0.00671 | 0.02601094 | 0.00586 | 0.20923 | 39.07804 | 51.0610162 | 87.4460141 | 9560.79729 | 70.8207207 | 84.1330556 | 26.1856053 | 1.30831339 | 90 | 14471.9801 | 107.999851 | 108.123166 | 64.1939495 | 2.42475584 | 180 | 277582.435 | 0 | 0 | 13 | 136 | 4.49468882 | 4.86939801 | 4.68204342 | 0 | Window | 0.00238283 | 0.0021969 | Alt_VSI | 17 | 0.10429448 | 0.1440678 | AI | 47 | 0.28834356 | 0.39830508 | ASI | 7 | 0.04294479 | 0.05932203 | TI_HSI | 42 | 0.25766871 | 0.3559322 | SSI | 0 | 0 | 0 | Window | 3 | 0.01840491 | 0.02542373 | RPM | 2 | 0.01226994 | 0.01694915
608 | 139.69895 | 0.22976801 | 0.2074 | 0.15119311 | 0.0199 | 0.99768 | 71 | 2724.27276 | 38.3700388 | 37.106766 | 20.8318854 | 0.52721396 | 82.5964419 | 3.8441 | 0.05414225 | 0.00672 | 0.11337185 | 0.00574 | 0.52246 | 143.54305 | 36.3411332 | 133.572691 | 41553.211 | 68.4566902 | 87.0448915 | 28.2589689 | 0.04361146 | 90 | 61884.9407 | 102.120364 | 100.883687 | 57.656037 | 0.73511 | 180 | 8227.60841 | 0 | 0 | 11 | 608 | 5.35115071 | 5.76353071 | 5.55734071 | 0 | SSI | 0.00512267 | 0.00529748 | Alt_VSI | 5 | 0.06849315 | 0.55555556 | AI | 2 | 0.02739726 | 0.22222222 | ASI | 0 | 0 | 0 | TI_HSI | 2 | 0.02739726 | 0.22222222 | SSI | 0 | 0 | 0 | Window | 0 | 0 | 0 | RPM | 0 | 0 | 0
508 | 122.67 | 0.24147638 | 0.22156 | 0.15057446 | 0.01978 | 0.98438 | 97 | 4796.5981 | 49.449465 | 43.945224 | 33.7873644 | 3.96660395 | 159.982717 | 2.47325 | 0.02549742 | 0.00677 | 0.07369456 | 0.00617 | 0.43494 | 125.14325 | 49.5987062 | 124.39209 | 31982.8505 | 63.0825454 | 80.161692 | 32.0168469 | 0.05687447 | 90 | 46417.7915 | 91.7347657 | 89.9008604 | 53.9669604 | 0.82504758 | 180 | 22674.501 | 0 | 0 | 11 | 508 | 5.45014569 | 5.85029 | 5.65021784 | 0 | TI_HSI | 0.00440035 | 0.00474343 | Alt_VSI | 3 | 0.12 | 0.33333333 | AI | 3 | 0.12 | 0.33333333 | ASI | 3 | 0.12 | 0.33333333 | TI_HSI | 0 | 0 | 0 | SSI | 0 | 0 | 0 | Window | 0 | 0 | 0 | RPM | 0 | 0 | 0
49 | 11.77226 | 0.2402502 | 0.22772 | 0.12130793 | 0.06042 | 0.55621 | 17 | 764.108733 | 44.9475726 | 41.2738243 | 18.3968382 | 12.34799 | 78.0893296 | 0.14191 | 0.00834765 | 0.00671 | 0.00645377 | 0.00641 | 0.03338 | 11.91417 | 82.9558171 | 21.235393 | 2664.62559 | 55.5130331 | 59.8173041 | 32.3824449 | 1.43942352 | 90 | 4283.83906 | 91.1455119 | 87.728798 | 44.3124908 | 4.31483481 | 175.050726 | 6896.80718 | 0 | 0 | 11 | 49 | 5.65875122 | 5.9014951 | 5.78012316 | 0 | RPM | 4.07E-04 | 4.42E-04 |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |   |  

</body>

</html>

**Comment by angeloryan** [comment]
Fixed, see commit e0133af. Issue happened due to incorrect String checks
