### ISSUE TITLE
Total number of fixations does not make sense for AOIs

### ISSUE THREAD

**Issue by ashkjones** [TheD2Lab/gazepoint-data-analysis#24]
The sum of "total number of fixations" across AOIs is larger than the "total number of fixations" in the overall DGM file. For participant 47, their DGM file has 1694 total fixations but their AOI total fixations add up to 4317. I don't think this makes sense when we don't have overlapping fixations. 

To calculate the number of fixations in the AOIs, I summed the values in the column A "Total Number of Fixations
" in the outputted `p47_approach_AOI_DGMs.csv` file.

**Comment by angeloryan** [comment]
See commit 009c1fd
