### ISSUE TITLE
DGMs use 0 as placeholder when a value isn't available

### ISSUE THREAD

**Issue by ashkjones** [TheD2Lab/gazepoint-data-analysis#25]
0 is used as the default value in the descriptive gaze measures when there is not enough fixations (such is the case with some AOIs).

This is an issue because 0 is not the same as does not exist. To quote Dr. Fu: "Substituting, say with zeros, will only make sense for measures of count, but not so much for others. For example, 0 degree is still a degree, where a bunch of zeros will bring down the average absolute/relative angles."

NaN is a better placeholder and already appears in some places in the DGMs (See p26's RPM StDev of saccade length). SPSS reads NaN as a missing value automatically. Please don't make Ashley check that each individual value is valid.

Sorry I did not catch this earlier. I assumed that DGMs were not calculated when there wasn't enough data because some participants are missing the RPM DGMs entirely. I did not notice other had 0s because there is just so much data to look at.

**Comment by angeloryan** [comment]
Fixed, 0s are now NaN. See 347642a and b6eba34

**Comment by ashkjones** [comment]
Reasoning for code implementation/decisions from Angelo:

>Also for now, I decided to return 0 for sum of empty lists (https://en.wikipedia.org/wiki/Empty_sum). I also changed the software to output data for pilots that never look at an AOI, doesn't change much since 90% of it is still NaN but I wanted it to be more explicit and in some cases I think the 0 can be meaningful.
